[outputFormats.llms]
  baseName       = "llms"
  mediaType      = "text/plain"
  isPlainText    = true
  notAlternative = true

[outputFormats.llmsfull]
  baseName       = "llms-full"
  mediaType      = "text/plain"
  isPlainText    = true
  notAlternative = true

[outputFormats.md]
  baseName       = "index"
  mediaType      = "text/markdown"
  isPlainText    = true
  notAlternative = true

[module]
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
